FoodForm/FoodForm/Models/Utilizadores.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace FoodForm.Models
{
    public class Utilizadores
    {
        public Utilizadores()
        {
            MinhasReceitas = new HashSet<Receitas>(); //coloca os dados na lista -> seleciona a os valores da tabela das receitas onde este utilizador está associado como criador
            ReceitasGostadas = new HashSet<Receitas>();
        }

        [Key]
        public int ID { get; set; }

        /// <summary>
        /// Nome que identifica o Utilizador
        /// </summary>
        [Required(ErrorMessage = "Preenchimento do {0} obrigatório.")]
        [StringLength(40, ErrorMessage ="O {0} não pode exceder os {1} caracteres.")]
        [RegularExpression("[A-ZÓÂÍ][a-zçáéíóúàèìòùãõäëïöüâêîôûñ]+(( | d[ao](s)? | e |-|'| d')[A-ZÓÂÍ][a-zçáéíóúàèìòùãõäëïöüâêîôûñ]+){1,3}")]
        public string Nome { get; set; }

        /// <summary>
        /// Referência remetente à localização do ficheiro de imagem deste utilizador
        /// </summary>
        [StringLength(255, ErrorMessage = "O nome do ficheiro não pode exceder os {1} caracteres.")]
        [RegularExpression("[A-Za-z0-9]+(.jpg|.png){1}")]
        public string Imagem { get; set; }

        /// <summary>
        /// Lista de receitas criadas por este utilizador
        /// </summary>
        [InverseProperty("Utilizador")]
        public ICollection<Receitas> MinhasReceitas { get; set; }

        /// <summary>
        /// Lista de receitas que este utilizador gostou
        /// </summary>
        public ICollection<Receitas> ReceitasGostadas { get; set; }

        /// <summary>
        /// String atribuida através do utilizador atenticado que corresponde ao utilizador atenticado
        /// </summary>
        public string UserID { get; set; }
    }
}

FoodForm/FoodForm/Controllers/ReceitasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FoodForm.Data;
using FoodForm.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Microsoft.AspNetCore.Http;

namespace FoodForm.Controllers
{
    [Authorize] //todos os métodos desta class ficaram protegidos em vez de ter de realizar a autorização individual de cada função.
    public class ReceitasController : Controller
    {
        /// <summary>
        /// Variavel que identifica a BD do nosso projecto
        /// </summary>
        private readonly FoodFormDB _context;

        /// <summary>
        /// variave que contem os dados do 'ambiente' do servidor.
        /// Em particular, onde estão os ficheiros guardados no disco rigido do servidor.
        /// </summary>
        private readonly IWebHostEnvironment _caminho;

        /// <summary>
        /// Recolher os dados remetentes á ao utlizador autenticado para esta variável
        /// </summary>
        private readonly UserManager<ApplicationUser> _userManager;

        public ReceitasController(FoodFormDB context, IWebHostEnvironment caminho, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
            _caminho = caminho;
        }

        // GET: Receitas
        [AllowAnonymous] //permite visualizar se o utilizador for anonimo -> anula o anotador [Authorize]
        public async Task<IActionResult> Index()
        {
            var foodFormDB = _context.Receitas.Include(r => r.Utilizador);
            return View(await foodFormDB.ToListAsync());
        }

        // GET: Receitas/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            //retorna o id utilizador
            Utilizadores Dono = _context.Utilizadores
                                         .Where(u => u.UserID == _userManager.GetUserId(User))
                                         .FirstOrDefault();
            //carrega para o viewbag
            ViewBag.ID_Dono = Dono.ID;

            //retorna uma o gosto feito por este utilizador a este post
            Gostos gostado = _context.Gostos
                .Where(u => u.UtilizadorFK == Dono.ID && u.ReceitaFK == id).FirstOrDefault();
            //carrega para o viewbag o estado do gosto no post
            if(gostado == null)
            {
                ViewBag.Liked = false;
            } else
            {
                ViewBag.Liked = true;
            }

            var receitas = await _context.Receitas
                .Include(r => r.Utilizador)
                .Include(c => c.ListaDeComentarios)
                .Include(g => g.ListaDeGostos)
                .FirstOrDefaultAsync(m => m.ID == id);
            
            if (receitas == null)
            {
                return NotFound();
            }

            return View(receitas);
        }

        // GET: Receitas/Create
        // Faz o GET da Interface para apresentar
        public IActionResult Create()
        {
            //envia o id do utilizador corrente 
            Utilizadores Dono = _context.Utilizadores
                                         .Where(u => u.UserID == _userManager.GetUserId(User))
                                         .FirstOrDefault();
            ViewBag.Owner = Dono.ID;
            //ViewData["Autor"] = new SelectList(_context.Utilizadores, "ID", "ID");
            return View();
        }

        // POST: Receitas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Titulo,Descricao,Imagem,Dificuldade,Tempo,PessoasServidas,Ingredientes,Autor")] Receitas receita, IFormFile fotoReceita)
        {
            //string que contem o caminho até a imagem
            string caminhoCompleto = "";
            bool haImagem = false;

            //porcessar a fotografia
            //será que há fotografia?->verificação de existencia de fotografia
            if (fotoReceita == null)
            {
                receita.Imagem = "no-food.png";
            }
            else
            {
                //especificação do content type
                if (fotoReceita.ContentType == "image/jpeg" || fotoReceita.ContentType == "image/png")
                {
                    //pepara o nome unico do ficheiro para guardar no disco rigido do servido
                    Guid g;
                    g = Guid.NewGuid();
                    string extensao = Path.GetExtension(fotoReceita.FileName).ToLower();
                    string nome = g.ToString() + extensao;
                    //onde guardar o ficheiro / a sua diretoria
                    caminhoCompleto = Path.Combine(_caminho.WebRootPath, "img\\receitas", nome);
                    //assosciar o nome do ficheiro á receita
                    receita.Imagem = nome;
                    //assinalar que existe imagem e é preciso guarda-la no disco
                    haImagem = true;
                }
                else
                {
                    receita.Imagem = "no-food.png";
                }
            }

            if (ModelState.IsValid)
            {
                _context.Add(receita);
                await _context.SaveChangesAsync();

                //se ha imagem, guardar no disco rigido
                if (haImagem)
                {
                    using var stream = new FileStream(caminhoCompleto, FileMode.Create);
                    await fotoReceita.CopyToAsync(stream);
                }

                return RedirectToAction(nameof(Index));
            }
            ViewBag.Owner = receita.Autor;
            return View(receita);
        }

        // GET: Receitas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //id do user
            Utilizadores Dono = _context.Utilizadores
                                        .Where(u => u.UserID == _userManager.GetUserId(User))
                                        .FirstOrDefault();
            ViewBag.Owner = Dono.ID;

            var receitas = await _context.Receitas.FindAsync(id);
            if (receitas == null)
            {
                return NotFound();
            }
            ViewData["Autor"] = new SelectList(_context.Utilizadores, "ID", "ID", receitas.Autor);
            return View(receitas);
        }

        // POST: Receitas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Titulo,Descricao,Imagem,Dificuldade,Tempo,PessoasServidas,Ingredientes,Autor")] Receitas receitas, IFormFile fotoReceita)
        {
            if (id != receitas.ID)
            {
                return NotFound();
            }

            //string que contem o caminho até a imagem
            string caminhoCompleto = "";
            bool haImagem = false;

            //porcessar a fotografia
            //será que há fotografia?->verificação de existencia de fotografia
            if (fotoReceita == null)
            {
                receitas.Imagem = "no-food.jpg";
            }
            else
            {
                //especificação do content type
                if (fotoReceita.ContentType == "image/jpeg" || fotoReceita.ContentType == "image/png")
                {
                    //pepara o nome unico do ficheiro para guardar no disco rigido do servido
                    Guid g;
                    g = Guid.NewGuid();
                    string extensao = Path.GetExtension(fotoReceita.FileName).ToLower();
                    string nome = g.ToString() + extensao;
                    //onde guardar o ficheiro / a sua diretoria
                    caminhoCompleto = Path.Combine(_caminho.WebRootPath, "img\\receitas", nome);
                    //assosciar o nome do ficheiro á receita
                    receitas.Imagem = nome;
                    //assinalar que existe imagem e é preciso guarda-la no disco
                    haImagem = true;
                }
                else
                {
                    receitas.Imagem = "no-food.jpg";
                }
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(receitas);
                    await _context.SaveChangesAsync();

                    //se ha imagem, guardar no disco rigido
                    if (haImagem)
                    {
                        using var stream = new FileStream(caminhoCompleto, FileMode.Create);
                        await fotoReceita.CopyToAsync(stream);
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReceitasExists(receitas.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Autor"] = new SelectList(_context.Utilizadores, "ID", "ID", receitas.Autor);
            return View(receitas);
        }

FoodForm/FoodForm/Views/Utilizadores/Create.cshtml
@model FoodForm.Models.Utilizadores

@{
    ViewData["Title"] = "Criar Utilizador";
}

<h1>Criar</h1>

<h4>Utilizador</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data" method="post"> @*ter a certeza de que o ficheiro chega ao controller atravez de enctype porque por default so envia texto*@
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagem" class="control-label"></label>
                <input type="file" name="fotoUser" accept=".jpg,.png" style="color:blue;"/>
                <span asp-validation-for="Imagem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-light" asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FoodForm/FoodForm/Views/Utilizadores/Delete.cshtml
@model FoodForm.Models.Utilizadores

@{
    ViewData["Title"] = "Apagar";
}

<h1>Apagar</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Utilizadores</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imagem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Imagem)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a class="btn btn-light" asp-action="Index">Voltar</a>
    </form>
</div>

FoodForm/FoodForm/Views/Utilizadores/Details.cshtml
@model FoodForm.Models.Utilizadores


@{
    ViewData["Title"] = "Details";
}

<h1>Detalhes</h1>

<div>
    <h4>Utilizadores</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imagem)
        </dt>
        <dd class = "col-sm-10">
            <img src="~/img/utilizadores/@Model.Imagem" height="256" alt="@Model.Nome" title="@Model.Nome" />
        </dd>
    </dl>
</div>

<h4>Receitas Criadas</h4>
@* Lista de receitas criadas *@

@if(Model.MinhasReceitas.Count == 0) //se não houver receitas associadas a esta conta ou seja o count for 0.
{
    <p>Oops... Não tens nehuma receita criada.</p>
}
else
{
    <table class="table">

        <tr>
            <td>Titulo</td>
        </tr>
        @foreach (var receita in Model.MinhasReceitas) //lista de todas as receitas criadas por este utilizador
        {
            <tr>
                <td><a asp-controller="Receitas" asp-action="Details" asp-route-id="@receita.ID">@receita.Titulo</a></td>
            </tr>
        }
    </table>
}



<div>
    @if (User.IsInRole("Moderador"))
    {<a class="btn btn-light" asp-action="Index">Voltar</a>}
    @if (User.IsInRole("Utilizador"))
    {<a class="btn btn-light" asp-action="Index" asp-controller="Home">Voltar</a>}
</div>

FoodForm/FoodForm/Views/Utilizadores/Edit.cshtml
@model FoodForm.Models.Utilizadores

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>

<h4>Utilizadores</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagem" class="control-label"></label>
                <input type="file" name="fotoUser" accept=".jpg,.png" style="color:blue;" />
                <span asp-validation-for="Imagem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    @if (User.IsInRole("Moderador"))
    {<a class="btn btn-light" asp-action="Index">Voltar</a>}
    @if (User.IsInRole("Utilizador"))
    {<a class="btn btn-light" asp-action="Index" asp-controller="Home">Voltar</a>}
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FoodForm/FoodForm/Views/Utilizadores/Index.cshtml
@model IEnumerable<FoodForm.Models.Utilizadores>

@{
    ViewData["Title"] = "Perfis de Utilizadores";
}

<h1>Perfis de Utilizadores</h1>

@if (User.IsInRole("Moderador"))
{
    <p>
        <a asp-action="Create">Create New</a>
    </p>
}
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Nome)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Imagem)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    <td>
                        <img src="~/img/utilizadores/@item.Imagem" height="80" alt="@item.Nome" title="@item.Nome" />
                    </td>
                    <td>
                        <a class="btn" asp-action="Edit" asp-route-id="@item.ID"><i class="fa fa-pencil" aria-hidden="true"></i></a> |
                        <a class="btn " asp-action="Details" asp-route-id="@item.ID"><i class="fa fa-eye" aria-hidden="true"></i></a> |
                        <a class="btn" asp-action="Delete" asp-route-id="@item.ID"><i class="fa fa-times" aria-hidden="true"></i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>