FoodForm/FoodForm/Models/Receitas.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace FoodForm.Models
{
    public class Receitas
    {
        public Receitas()
        {
            ListaDeComentarios = new HashSet<Comentarios>();
        }

        [Key]
        public int ID { get; set; }

        /// <summary>
        /// Nome do prato ou receita descrita no post
        /// </summary>
        [Required(ErrorMessage = "Preenchimento do {0} obrigatório.")]
        [StringLength(30, ErrorMessage = "O Titulo não pode exceder os {1} caracteres.")]
        [RegularExpression("[A-ZÓÂÍa-zçáéíóúàèìòùãõäëïöüâêîôûñ ]+")]
        public string Titulo { get; set; }

        /// <summary>
        /// Receita effectiva e/ou modo de praparação da receita
        /// </summary>
        [Required(ErrorMessage = "Preenchimento da {0} obrigatória.")]
        public string Descricao { get; set; }

        /// <summary>
        /// Referencia da imagem respectiva ao prato
        /// </summary>
        [StringLength(255, ErrorMessage = "O nome do ficheiro não pode exceder os {1} caracteres.")]
        [RegularExpression("[A-Za-z0-9]+(.jpg|.png){1}", ErrorMessage ="Esse formato de ficheiro não é válido.")]
        public string Imagem { get; set; }

        /// <summary>
        /// Dificuldade de confeção da receita geralmente categorizado por Fácil, Média, Difícil
        /// </summary>
        [Required(ErrorMessage = "Preenchimento da {0} obrigatória.")]
        [RegularExpression("(Fácil|Intermédio|Difícil){1}")]
        public string Dificuldade { get; set; }

        /// <summary>
        /// Tempo médio que demora a preparação e cofeção do prato em minutos
        /// </summary>
        [Required(ErrorMessage = "Preenchimento do {0} obrigatório.")]
        [RegularExpression("[1-9]{1}[0-9]{0,3}", ErrorMessage ="Entre 1 e 4 dígitos.")]
        public int Tempo { get; set; }

        /// <summary>
        /// Numero de pessoas que a dose referenciada na receita serve normalmente
        /// </summary>
        [Required(ErrorMessage = "Preenchimento das {0} é obrigatório.")]
        [RegularExpression("[1-9]{1}[0-9]{0,1}", ErrorMessage = "Numero de pessoas deve ser entre 1 e 99.")]
        public int PessoasServidas { get; set; }

        /// <summary>
        /// Ingredientes base presentes na receita que o autor queira especificar
        /// </summary>
        [RegularExpression("[A-ZÓÂÍa-zçáéíóúàèìòùãõäëïöüâêîôûñ ]+[;]", ErrorMessage ="Os ingredientes devem estar separados por ';'.")]
        public string Ingredientes { get; set; }

        /// <summary>
        /// Utilizador que criou esta receita
        /// </summary>
        [ForeignKey(nameof(Utilizador))]
        public int Autor { get; set; }
        public Utilizadores Utilizador { get; set; }

        /// <summary>
        /// Lista de comentários feitos a esta receita
        /// </summary>
        public ICollection<Comentarios> ListaDeComentarios { get; set; }

        /// <summary>
        /// Lista de gostos relacionados com esta receita
        /// </summary>
        public ICollection<Gostos> ListaDeGostos{ get; set; }
    }
}

FoodForm/FoodForm/Controllers/ComentariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FoodForm.Data;
using FoodForm.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Xceed.Wpf.Toolkit;

namespace FoodForm.Controllers
{
    [Authorize]
    public class ComentariosController : Controller
    {
        private readonly FoodFormDB _context;

        private readonly UserManager<ApplicationUser> _userManager;

        public ComentariosController(FoodFormDB context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Comentarios
        [Authorize(Roles ="Moderador")]
        public async Task<IActionResult> Index()
        {
            var foodFormDB = _context.Comentarios.Include(c => c.Receita).Include(c => c.Utilizador);
            return View(await foodFormDB.ToListAsync());
        }

        // GET: Comentarios/Details/5
        [Authorize(Roles = "Moderador")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comentarios = await _context.Comentarios
                .Include(c => c.Receita)
                .Include(c => c.Utilizador)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (comentarios == null)
            {
                return NotFound();
            }

            return View(comentarios);
        }

        // GET: Comentarios/Create
        public IActionResult Create()
        {
            ViewData["ReceitaFK"] = new SelectList(_context.Receitas, "ID", "Descricao");
            ViewData["UtilizadorFK"] = new SelectList(_context.Utilizadores, "ID", "Email");
            return View();
        }

        // POST: Comentarios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Conteudo")] Comentarios comentarios, int id)
        {
            if (ModelState.IsValid)
            {
                //Utilizador que está a comentar
                Utilizadores user = _context.Utilizadores
                    .Where(u => u.UserID == _userManager.GetUserId(User))
                    .FirstOrDefault();
                //Receita que está a ser comentada
                Receitas receita = _context.Receitas
                    .Where(r => r.ID == id)
                    .FirstOrDefault();

                if( user == null || receita == null)
                {
                    return NotFound();
                }

                //criação do comentario
                var comentario = new Comentarios
                {
                    Conteudo = comentarios.Conteudo,
                    Data = DateTime.Now,
                    UtilizadorFK = user.ID,
                    ReceitaFK = receita.ID
                };

                _context.Comentarios.Add(comentario);

                await _context.SaveChangesAsync();

                return RedirectToAction("Details", "Receitas", new { Id = id });
            }
            return NotFound();
        }

        // GET: Comentarios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comentario = await _context.Comentarios
                .Include(c => c.Receita)
                .Include(c => c.Utilizador)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (comentario == null)
            {
                return NotFound();
            }

            return View();
        }

        // POST: Comentarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var comentario = await _context.Comentarios.FindAsync(id);
            _context.Comentarios.Remove(comentario);
            await _context.SaveChangesAsync();

            //volta á pagina da receita
            return RedirectToAction("Details", "Receitas", new { Id = comentario.ReceitaFK });
        }

        private bool ComentariosExists(int id)
        {
            return _context.Comentarios.Any(e => e.ID == id);
        }
    }
}

FoodForm/FoodForm/Controllers/DenunciasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FoodForm.Data;
using FoodForm.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace FoodForm.Controllers
{
    [Authorize]
    public class DenunciasController : Controller
    {
        private readonly FoodFormDB _context;

        private readonly UserManager<ApplicationUser> _userManager;

        public DenunciasController(FoodFormDB context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        
        // GET: Denuncias
        [Authorize(Roles = "Moderador")]
        public async Task<IActionResult> Index()
        {
            var foodFormDB = _context.Denuncias.Include(d => d.Receita).Include(d => d.Utilizador);
            return View(await foodFormDB.ToListAsync());
        }

        // GET: Denuncias/Details/5
        [Authorize(Roles = "Moderador")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var denuncias = await _context.Denuncias
                .Include(d => d.Receita)
                .Include(d => d.Utilizador)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (denuncias == null)
            {
                return NotFound();
            }

            return View(denuncias);
        }

        // GET: Denuncias/Create
        [Authorize(Roles = "Utilizador")]
        public IActionResult Create()
        {
            ViewData["ReceitaFK"] = new SelectList(_context.Receitas, "ID", "Descricao");
            ViewData["UtilizadorFK"] = new SelectList(_context.Utilizadores, "ID", "Email");
            return View();
        }

        // POST: Denuncias/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Utilizador")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Data,Conteudo,UtilizadorFK,ReceitaFK")] Denuncias denuncias, int id)
        {
            if (ModelState.IsValid)
            {
                //Utilizador que está a denunciar
                Utilizadores user = _context.Utilizadores
                    .Where(u => u.UserID == _userManager.GetUserId(User))
                    .FirstOrDefault();
                //Receita que está a ser denunciao
                Receitas receita = _context.Receitas
                    .Where(r => r.ID == id)
                    .FirstOrDefault();

                if (user == null || receita == null)
                {
                    return NotFound();
                }

                //criação da denuncia
                var denuncia = new Denuncias
                {
                    Conteudo = denuncias.Conteudo,
                    Data = DateTime.Now,
                    UtilizadorFK = user.ID,
                    ReceitaFK = receita.ID
                };


                _context.Denuncias.Add(denuncia);

                await _context.SaveChangesAsync();

                return RedirectToAction("Details", "Receitas", new { Id = id });
            }
            return NotFound();
        }

        // GET: Denuncias/Delete/5
        [Authorize(Roles = "Moderador")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var denuncias = await _context.Denuncias
                .Include(d => d.Receita)
                .Include(d => d.Utilizador)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (denuncias == null)
            {
                return NotFound();
            }

            return View(denuncias);
        }

        // POST: Denuncias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Moderador")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var denuncias = await _context.Denuncias.FindAsync(id);
            _context.Denuncias.Remove(denuncias);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DenunciasExists(int id)
        {
            return _context.Denuncias.Any(e => e.ID == id);
        }
    }
}

FoodForm/FoodForm/Controllers/GostosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FoodForm.Data;
using FoodForm.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace FoodForm.Controllers
{
    [Authorize]
    public class GostosController : Controller
    {
        private readonly FoodFormDB _context;

        private readonly UserManager<ApplicationUser> _userManager;

        public GostosController(FoodFormDB context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Gostos
        [Authorize(Roles = "Moderador")]
        public async Task<IActionResult> Index()
        {
            var foodFormDB = _context.Gostos.Include(g => g.Receita).Include(g => g.Utilizador);
            return View(await foodFormDB.ToListAsync());
        }

        // GET: Gostos/Details/5
        [Authorize(Roles = "Moderador")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gostos = await _context.Gostos
                .Include(g => g.Receita)
                .Include(g => g.Utilizador)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (gostos == null)
            {
                return NotFound();
            }

            return View(gostos);
        }

        // POST: Gostos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Utilizador")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int id)
        {
            //Utilizador que está a gostar
            Utilizadores user = _context.Utilizadores
                .Where(u => u.UserID == _userManager.GetUserId(User))
                .FirstOrDefault();
            //Receita que está a ser gostado
            Receitas receita = _context.Receitas
                .Where(r => r.ID == id)
                .FirstOrDefault();

            if(user == null || receita == null){
                return NotFound();
            }
            else
            {
                //criar o gosto
                var gosto = new Gostos
                {
                    ReceitaFK = receita.ID,
                    UtilizadorFK = user.ID,
                    Gosto = true
                };

                _context.Gostos.Add(gosto);
                await _context.SaveChangesAsync();
                //Redireciona para página da receita
                return RedirectToAction("Details", "Receitas", new { Id = id });
            }
        }

        // POST: Gostos/Delete/5
        [Authorize(Roles = "Utilizador")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            //Utilizador que está a gostar
            Utilizadores user = _context.Utilizadores
                .Where(u => u.UserID == _userManager.GetUserId(User))
                .FirstOrDefault();
            //Receita que está a ser gostada
            Receitas receita = _context.Receitas
                .Where(r => r.ID == id)
                .FirstOrDefault();
            //Gosto a ser apagado
            Gostos gosto = _context.Gostos.Where(g => g.ReceitaFK == receita.ID && g.UtilizadorFK == user.ID).FirstOrDefault();

            _context.Gostos.Remove(gosto);
            await _context.SaveChangesAsync();
            //Redireciona para a página da receita
            return RedirectToAction("Details","Receitas",new {Id = id});
        }

        private bool GostosExists(int id)
        {
            return _context.Gostos.Any(e => e.ID == id);
        }
    }
}

FoodForm/FoodForm/Views/Receitas/Create.cshtml
@model FoodForm.Models.Receitas

@{
    ViewData["Title"] = "Criar";
}

<h4>Criar Receita</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form id="CreateReceita" asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Título</label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Descrição</label>
                <textarea asp-for="Descricao" class="form-control" form="CreateReceita"></textarea>
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagem" class="control-label"></label>
                <input type="file" name="fotoReceita" accept=".jpg,.png" style="color:blue;" />
                <span asp-validation-for="Imagem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dificuldade" class="control-label"></label>
                <select asp-for="Dificuldade" class="form-control">
                    <option value="Fácil">Fácil</option>
                    <option value="Intermédio">Intermédio</option>
                    <option value="Difícil">Difícil</option>
                </select>
                <span asp-validation-for="Dificuldade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tempo" class="control-label">Tempo (em minutos)</label>
                <input asp-for="Tempo" class="form-control" min="1" />
                <span asp-validation-for="Tempo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PessoasServidas" class="control-label">Nº de pessoas servidas</label>
                <input asp-for="PessoasServidas" class="form-control" min="1" />
                <span asp-validation-for="PessoasServidas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ingredientes" class="control-label"></label>
                <input asp-for="Ingredientes" class="form-control" />
                <span asp-validation-for="Ingredientes" class="text-danger"></span>
            </div>
            @if (User.IsInRole("Moderador"))
            {
                <div class="form-group">
                    <label asp-for="Autor" class="control-label"></label>
                    <select asp-for="Autor" class="form-control" asp-items="ViewBag.Autor"></select>
                </div>
            }
            else
            {
                <div class="form-group">
                    <input asp-for="Autor" class="form-control" value="@ViewBag.Owner" hidden/>
                </div>
            }
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Home" asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FoodForm/FoodForm/Views/Receitas/Delete.cshtml
@model FoodForm.Models.Receitas

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Receitas</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imagem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Imagem)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dificuldade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dificuldade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tempo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tempo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PessoasServidas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PessoasServidas)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ingredientes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ingredientes)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Utilizador)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Utilizador.ID)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a class="btn btn-light" asp-action="Index">Voltar</a>
    </form>
</div>

FoodForm/FoodForm/Views/Receitas/Details.cshtml
@model FoodForm.Models.Receitas

@{
    ViewData["Title"] = "Details";
}

<h1>Receita</h1>
<hr />
<div class="container-fluid">
    <div class="row">
        <dl class="col receitaContainer">
            <dd class="col-sm-10">
                <img src="~/img/receitas/@Model.Imagem" height="256" alt="@Model.Titulo" title="@Model.Titulo" />
            </dd>
            <dd class="col-sm-12">
                <h2>@Html.DisplayFor(model => model.Titulo)</h2>
            </dd>
            <dd class="col-sm-10">
                <span class="icons">
                    <i class="fa fa-signal" aria-hidden="true"></i> 
                    @Html.DisplayFor(model => model.Dificuldade)
                </span>
                <span class="icons">
                    <i class="fa fa-clock-o" aria-hidden="true"></i> 
                    @Html.DisplayFor(model => model.Tempo)min
                </span>
                <span class="icons">
                    <i class="fa fa-users" aria-hidden="true"></i> 
                    @Html.DisplayFor(model => model.PessoasServidas)
                </span>
            </dd>
            <dd>
                @if (User.Identity.IsAuthenticated && !User.IsInRole("Moderador"))
                {
                    //botão de like que so pode ser acedido pelos utilizadores
                    <div class="likeContainer">

                        @if (ViewBag.Liked == true) //enquato tiver sido gostado apresenta o icon verde e apresenta a opção de apagar o like da base de dados
                        {
                            <form asp-action="Delete" asp-controller="Gostos" method="post">
                                <input type="hidden" asp-for="ID" />
                                <button type="submit" value="Gostei" class="btn">
                                    <i class="fa fa-thumbs-o-up" aria-hidden="true" style="color:green"></i>
                                    @Model.ListaDeGostos.Count Gosto(s)
                                </button>
                            </form>
                        }
                        else  //enquato não tiver sido gostado apresenta o icon verde e apresenta a opção de criar o like na base de dados
                        {
                            <form asp-action="Create" asp-controller="Gostos" method="post">
                                <input type="hidden" asp-for="ID" />
                                <button type="submit" value="Gostar" class="btn">
                                    <i class="fa fa-thumbs-o-up" aria-hidden="true" style="color:blue"></i>
                                    @Model.ListaDeGostos.Count Gosto(s)
                                </button>
                            </form>
                        }
                    </div>
                }
            </dd>
            <dd class="col-sm-12">
                <p>@Html.DisplayFor(model => model.Descricao)</p>
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Ingredientes)
            </dt>
            <dd class="col-sm-10">
                @if(Model.Ingredientes != null){ //separa a string dos ingredientes em list items desde que haja ingredientes identificados
                    <ul>
                        @foreach (var ingredient in Model.Ingredientes.Split(";")){
                            @if(ingredient != ""){
                                <li>
                                    @ingredient
                                </li>
                            }
                        }
                    </ul>
                } else {
                    <span>Nao existem ingredientes para esta receita.</span> // no caso de nao haver ingredientes identificados
                }
            </dd>
            <dd class="col-sm-10">
                <i class="fa fa-user" aria-hidden="true"></i>
                @Html.DisplayFor(model => model.Utilizador.Nome)
            </dd>
        </dl>
        <div class="col comentariosContainer">

            @if (User.Identity.IsAuthenticated) //so pode visualizar se for autenticado
            {
                //so pode ser comentado se for utilizador
                <h2>Comentários @if (User.IsInRole("Utilizador")) {<a class="btn btn-light" asp-controller="Comentarios" asp-action="Create" asp-route-id="@Model.ID"><span>✏️</span></a>}</h2>
                <hr />
                @if (Model.ListaDeComentarios.Count == 0) //se não houver receitas associadas a esta conta ou seja o count for 0.
                {
                    <p>Sem Comentários. Faz o primeiro comentário!</p>
                }
                else
                {
                    @foreach (var item in Model.ListaDeComentarios) //lista de comentarios
                    { 
                        //por cada comentario apresenta o nome do autor, o conteudo e quando foi escrito
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="card">
                                    <div class="card-body">
                                        <h5 class="card-title">@Html.DisplayFor(modelItem => item.Utilizador.Nome)</h5>
                                        <p class="card-text">@Html.DisplayFor(modelItem => item.Conteudo)</p>
                                        <p>@Html.DisplayFor(modelItem => item.Data)</p>
                                        @if (User.Identity.IsAuthenticated && Model.Autor == ViewBag.ID_Dono || User.IsInRole("Moderador"))
                                            //permite apagar se for o dono do comentario ou o moderador
                                        {
                                            <a class="btn btn-danger" asp-controller="Comentarios" asp-action="Delete" asp-route-id="@item.ID">
                                                <span>Apagar</span>
                                            </a>
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                }
            }
        </div>

    </div>

    <a class="btn btn-light" asp-action="Index">Voltar</a>

    @if (User.Identity.IsAuthenticated && Model.Autor == ViewBag.ID_Dono)
    {
        <a class="btn btn-light" asp-action="Edit" asp-route-id="@Model.ID">Editar</a>
    }
    @if (User.Identity.IsAuthenticated && User.IsInRole("Moderador") || User.Identity.IsAuthenticated && Model.Autor == ViewBag.ID_Dono)
    {
        <a class="btn btn-light" asp-action="Delete" asp-route-id="@Model.ID">Apagar</a>
    }
    @if (User.Identity.IsAuthenticated && !User.IsInRole("Moderador"))
    {
        <a class="btn btn-dark" asp-action="Create" asp-controller="Denuncias" asp-route-id="@Model.ID">Denunciar</a>
    }
</div>

FoodForm/FoodForm/Views/Receitas/Index.cshtml
@model IEnumerable<FoodForm.Models.Receitas>

@{
    ViewData["Title"] = "Receitas";
}

<style>
.flexed {
    display: flex;
    flex: 1;
    align-items: flex-start;
    justify-content: space-around;
    flex-direction: row;
    flex-wrap: wrap;
}

.flexed-item {
    flex: 1 0 21%;
    align-self: auto;
    padding: 20px;
    margin: 20px;
    max-width: calc(100% * (1/4) - 10px - 1px);
}
.icons {
    margin-right: 5px:
}
</style>

<div class="flexed">
    @foreach (var item in Model){
        <div class="card flexed-item" style="width: 18rem;">
            <img src="~/img/receitas/@item.Imagem" class="card-img-top"  alt="@item.Titulo" title="@item.Titulo" >
            <div class="card-body">
                <h5 class="card-title text-truncate">
                    @Html.DisplayFor(modelItem => item.Titulo)
                </h5>
                <p class="card-text">
                    <span class="icons">
                        <i class="fa fa-signal" aria-hidden="true"></i> 
                        @Html.DisplayFor(modelItem => item.Dificuldade)
                    </span><br/>
                    <span class="icons">
                        <i class="fa fa-clock-o" aria-hidden="true"></i> 
                        @Html.DisplayFor(modelItem => item.Tempo)min
                    </span><br/>
                    <span class="icons">
                        <i class="fa fa-users" aria-hidden="true"></i> 
                        @Html.DisplayFor(modelItem => item.PessoasServidas)
                    </span>
                </p>
                <a class="btn btn-primary" asp-action="Details" asp-route-id="@item.ID">Ver</a>
            </div>
        </div>
    }
</div>